vich_uploader:
    db_driver: orm
    metadata:
        type: attribute
    mappings:
        picture:
            uri_prefix: "%upload_images%"
            upload_destination: "%kernel.project_dir%/public%upload_images% "
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
