version: '3'

services:
  database:
    image: 'mariadb:10.3'
    environment:
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_password
      MYSQL_DATABASE: db_name
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - db-data:/var/lib/mysql/:rw
    ports:
      - '3307:3306'
volumes:
  db-data:

